config/routes.rb
Rails.application.routes.draw do
  
  get 'music_finder_pages/index'

  get 'sites/index' => 'sites#index', as: :sites

  get '/sites/music_finder' => 'musicfinder#index', as: :musicfinder

  get 'sites/document_organizer'

  get 'sites/professional_services'

  root 'sites#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musicfinder_controller.rb
class MusicfinderController < ApplicationController

	def index
	end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
  end

  def music_finder
  end

  def document_organizer
  end

  def professional_services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musicfinder_helper.rb
module MusicfinderHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= sites_url %> ">Max Pleaner</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <% if Rails.env.production? %>
            <% url = "http://maxpleaner.github.io" %>
          <% else %>
            <% url = "http://localhost:4000" %> 
          <% end %>
            <%= link_to 'Blog', url %>
        </li>
        <li><a href="/sites/professional_services">Professional Services</a></li>
        <li><a href="/sites/music_finder">Music-Finder</a></li>
        <li><a href="/sites/document_organizer">Document-Organizer</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MaxPleaner</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="http://getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= render 'layouts/navbar' %> 

<div class="container container-xs-height">
  <div class="pre-background"></div>
  <div class="background"></div>
  <div class="starter-template">
   <%= yield %>
  </div>
</div>

<script src="http://getbootstrap.com/dist/js/bootstrap.js"></script>
</body>
</html>

app/views/musicfinder/_instructions.html.erb
<strong><em>Important: </strong>if your current url does not include a "city" parameter (in the form of "?city=CITYNAME" appended to /map/index) this page will not work correctly. Here's what you need to do: </em>
	<ul>
		<li>
			Add a city parameter to the URL and resubmit the page request. Note that this app's parameter-parsing capabilities are weak and so, for simplicity's sake, try to stick to single-word cities that are likely to have events on last.fm
		</li>
	</ul>

app/views/musicfinder/index.html.erb
<div class="row">

	<div class="col-xs-12 text-center first box box-blue">
		<h1>Music Event Finder</h1>
	</div>

</div>

<div class="row">	

	<div class="minheight maxbox-container text-center box box-red col-xs-2">
		<button type="button" class="instruction-button maxbox">Click here to show instructions</button>
	</div>
	
	<div class="col-xs-10 box box-red instruction-content hidden-content">
		<%= render 'instructions' %> 
	</div>

</div>

app/views/sites/document_organizer.html.erb
<h1>Sites#document_organizer</h1>
<p>Find me in app/views/sites/document_organizer.html.erb</p>

app/views/sites/index.html.erb
	<div class="first box box-blue">
    <h1>
    	Web Development Projects and Professional Services
    </h1>
	</div>
  <!-- <hr> -->

  <div class="box box-blue">
    <p class="lead"> 
			I can build you a complex web application with services specially tailored to comprehensively fulfill the idiosyncratic needs of your business or organization. 
    </p>
  </div>
  <!-- <hr> -->

	<div class="box box-red">
		<p>
			<strong>
				Here's a quick rundown of news regarding the development of this site
			</strong>
			<ul class="news_ul">
				<li>
					<em>
						May 10, 2014:
					</em> 
					I've been working alot on the blog and am happy with the progress I've made (it's workable). I would like to keep the blog hosted on this domain but I think that is an issue I will have to sort out through server configuration as it doesn't seem anybody has a workable tutorial for integrating Octopress-generated content into Rails. The blog is hosted on maxpleaner.github.io and you can click the 'blog' link in the navbar to get there. Next I'm going to try and get my Music-Finder site integrated into this site.  
				</li>				
				<li>
					<em>
						May 4, 2014:
					</em> 
					I spent a good amount of time refactoring my styles and now I have a good app-wide layout scheme and it's possible to format individual pages using only a couple styles (like .box, .box-red, and only a couple more). I would like to get started on migrating my music-finder app over to this page, but first I think i will look into blog engines. I'd like to start out with a blog that has tags and possibly some other common features like social buttons. 
				</li>
				<li>
					<em>
						May 2, 2014:
					</em> 
					I have this app up on heroku at maxpleaner.heroku.com and also on github at github.com/maxpleaner/homepage. Bootstrap styles are working correctly using the CDN. I have basically 5 blank pages I now need to fill out with content. Stay tuned!
				</li>
			</ul>
		</p>
	</div>
	<!-- <hr> -->

	<div class="last box box-green">
	  <em>
	  	<small>
	  		Note:		I made this page using Twitter Bootstrap and I am glad that I was able to use a template and easily knock this one out. I have a lot to learn when it comes to front-end design, but I am happy having produced this because I can now focus on building the other core features of the site: the blog, the professional services section, and the two "sample" apps! Check out the links in the navbar to see what's been happening.
	  	</small>
	  </em>
	</div>

app/views/sites/professional_services.html.erb
<h1>Sites#professional_services</h1>
<p>Find me in app/views/sites/professional_services.html.erb</p>